DatabaseManager.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace DatabaseManager.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

DatabaseManager.Web/Pages/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NToastNotify;

namespace DatabaseManager.Web.Pages
{
    public class IndexModel(IUnitOfWork unitOfWork, IToastNotification toastNotification) : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public string OsVersion { get; set; }

        [BindProperty(SupportsGet = true)]
        public string OsArchitecture { get; set; }

        [BindProperty(SupportsGet = true)]
        public string OsCores { get; set; }

        [BindProperty(SupportsGet = true)]
        public string OsRam { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DbVersion { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DbCores { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DbRam { get; set; }

        [BindProperty(SupportsGet = true)]
        public string DbSize { get; set; }

        [BindProperty]
        public string SqlCommand { get; set; }

        public void OnGet()
        {
            var osData = GetDataForOs();
            OsVersion = osData[0] + " " + osData[1];
            OsArchitecture = osData[2];
            OsCores = osData[3];
            OsRam = osData[4];

            var dbData = GetDataForDb();
            DbVersion = dbData[0] + " " + dbData[1];
            DbSize = dbData[2];
            DbRam = dbData[3];
            DbCores = dbData[4];
        }

        public IActionResult OnPostExecute()
        {
            try
            {
                var results = new List<Dictionary<string, object>>();
                using var dbConnection = unitOfWork.GetDbConnection();
                dbConnection.Open();
                using var command = dbConnection.CreateCommand();
                command.CommandText = SqlCommand;
                using var reader = command.ExecuteReader();
                while (reader.Read())
                {
                    var row = new Dictionary<string, object>();
                    for (int i = 0; i < reader.FieldCount; i++)
                    {
                        row[reader.GetName(i)] = reader.GetValue(i);
                    }
                    results.Add(row);
                }
                toastNotification.AddSuccessToastMessage("Successfully executed SQL-Query.");
                ViewData["Results"] = results;
            }
            catch (Exception e)
            {
                toastNotification.AddErrorToastMessage($"Error while executing SQL-Query:\n{e.Message}");
            }

            OnGet();
            return Page();
        }

        private string[] GetDataForOs()
        {
            var result = new List<string>();

            using var dbConnection = unitOfWork.GetDbConnection();
            dbConnection.Open();
            using var command = dbConnection.CreateCommand();
            command.CommandText = @"
                SELECT host_distribution, host_release, host_architecture
                FROM sys.dm_os_host_info;";
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    result.Add(reader.GetString(0)); // host_distribution
                    result.Add(reader.GetString(1)); // host_release
                    result.Add(reader.GetString(2)); // host_architecture
                }
            }
            command.CommandText = @"
                SELECT CAST(cpu_count AS NVARCHAR(50)), FORMAT((physical_memory_kb / 1024.0 / 1024.0), 'N2') as physical_memory_gb
                FROM sys.dm_os_sys_info;";
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    result.Add(reader.GetString(0)); // cpu_count
                    result.Add(reader.GetString(1)); // physical_memory_kb
                }
            }
            dbConnection.Close();
            return result.ToArray();
        }

        private string[] GetDataForDb()
        {
            var result = new List<string>();

            using var dbConnection = unitOfWork.GetDbConnection();
            dbConnection.Open();
            using var command = dbConnection.CreateCommand();
            command.CommandText = @"
                SELECT SERVERPROPERTY('ProductVersion'), SERVERPROPERTY('Edition');";
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    result.Add(reader.GetString(0)); // ProductVersion
                    result.Add(reader.GetString(1)); // Edition
                }
            }
            command.CommandText = @"
                SELECT FORMAT(SUM(size * 8.0 / 1024 / 1024), 'N2') AS TotalSizeInGB
                FROM sys.master_files;";
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    result.Add(reader.GetString(0)); // size
                }
            }

            command.CommandText = @"
                SELECT FORMAT((physical_memory_in_use_kb / 1024 / 1024), 'N2') AS MemoryUsageInGB 
                FROM sys.dm_os_process_memory;";
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    result.Add(reader.GetString(0)); // UsedMemory
                }
            }

            command.CommandText = @"
                SELECT CAST(COUNT(*) AS NVARCHAR(20)) AS NumberOfCores
                FROM sys.dm_os_schedulers 
                WHERE status = 'VISIBLE ONLINE';";
            using (var reader = command.ExecuteReader())
            {
                while (reader.Read())
                {
                    result.Add(reader.GetString(0)); // UsedCores
                }
            }
            dbConnection.Close();
            return result.ToArray();
        }
    }
}

DatabaseManager.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home";
}

<div class="container p-5">
    <div class="row pt-3 justify-content-center align-items-center">
        <div class="col-5 mr-2" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-right: 10px;">
            <h3 class="text-primary">OS Overview</h3>
            <p>OS Version: <span class="text-secondary">@Model.OsVersion</span></p>
            <p>OS Architecture: <span class="text-secondary">@Model.OsArchitecture</span></p>
            <p>Total Cores: <span class="text-secondary">@Model.OsCores</span></p>
            <p>Total RAM: <span class="text-secondary">@Model.OsRam GB</span></p>
        </div>
        <div class="col-5 ml-2" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-left: 10px;">
            <h3 class="text-primary">DB Overview</h3>
            <p>DB Version: <span class="text-secondary"> @Model.DbVersion</span></p>
            <p>Used Space: <span class="text-secondary"> @Model.DbSize GB</span></p>
            <p>Used Cores: <span class="text-secondary"> @Model.DbCores</span></p>
            <p>Used RAM: <span class="text-secondary"> @Model.DbRam GB</span></p>
        </div>
        <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-top: 20px;">
            <h3 class="text-primary">SQL Query</h3>
            <form asp-page-handler="Execute" method="post">
                <input asp-for="SqlCommand" type="text" class="form-control" name="sqlCommand" placeholder="Enter your SQL-Command here..." />
                <button type="submit" class="btn btn-outline-warning" style="margin-top: 10px">
                    <div class="d-flex justify-content-center">
                        <i class="bi bi-database-check"></i>&nbsp;Execute
                    </div>
                </button>
            </form>
        </div>
        <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-top: 20px; overflow: auto;">
            <h3 class="text-secondary">Result</h3>
            @if (ViewData["Results"] is List<Dictionary<string, object>> {Count: > 0 } results)
            {
                <table class="table">
                    <thead>
                    <tr>
                        @foreach (var key in results[0].Keys)
                        {
                            <th>@key</th>
                        }
                    </tr>
                    </thead>
                    <tbody>
                    @foreach (var row in results)
                    {
                        <tr>
                            @foreach (var column in row)
                            {
                                <td>@column.Value</td>
                            }
                        </tr>
                    }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>