DatabaseManager.Web/Pages/Generators/Customer/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseManager.Web.Pages.Generators.Customer
{
    public class IndexModel(IUnitOfWork unitOfWork, IConfiguration configuration) : CustomPageModel<IndexModel>(configuration)
    {
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public bool FillOptionalProperties { get; set; }
        [BindProperty]
        public bool SetReferences { get; set; }
        [BindProperty]
        public string FirstName { get; set; }
        [BindProperty]
        public string LastName { get; set; }
        [BindProperty]
        public string Email { get; set; }
        [BindProperty]
        public string MiddleName { get; set; }
        [BindProperty]
        public int MiddleNameChance { get; set; }
        [BindProperty]
        public string SecondaryEmail { get; set; }
        [BindProperty]
        public int SecondaryEmailChance { get; set; }
        [BindProperty]
        public string PhoneNumber { get; set; }
        [BindProperty]
        public int PhoneNumberChance { get; set; }
        [BindProperty]
        public string SecondaryPhoneNumber { get; set; }
        [BindProperty]
        public int SecondaryPhoneNumberChance { get; set; }
        [BindProperty]
        public string DateOfBirth { get; set; }
        [BindProperty]
        public int DateOfBirthChance { get; set; }
        [BindProperty]
        public string Gender { get; set; }
        [BindProperty]
        public int GenderChance { get; set; }
        [BindProperty]
        public string Nationality { get; set; }
        [BindProperty]
        public int NationalityChance { get; set; }
        [BindProperty]
        public string AddressLine1 { get; set; }
        [BindProperty]
        public int AddressLine1Chance { get; set; }
        [BindProperty]
        public string AddressLine2 { get; set; }
        [BindProperty]
        public int AddressLine2Chance { get; set; }
        [BindProperty]
        public string City { get; set; }
        [BindProperty]
        public int CityChance { get; set; }
        [BindProperty]
        public string State { get; set; }
        [BindProperty]
        public int StateChance { get; set; }
        [BindProperty]
        public string Country { get; set; }
        [BindProperty]
        public int CountryChance { get; set; }
        [BindProperty]
        public string PostalCode { get; set; }
        [BindProperty]
        public int PostalCodeChance { get; set; }
        [BindProperty]
        public bool IsActive { get; set; }
        [BindProperty]
        public int IsActiveChance { get; set; }
        [BindProperty]
        public string LastOnline { get; set; }
        [BindProperty]
        public int LastOnlineChance { get; set; }
        [BindProperty]
        public string CreatedAt { get; set; }
        [BindProperty]
        public int CreatedAtChance { get; set; }
        [BindProperty]
        public string UpdatedAt { get; set; }
        [BindProperty]
        public int UpdatedAtChance { get; set; }
        [BindProperty]
        public string PreferredLanguage { get; set; }
        [BindProperty]
        public int PreferredLanguageChance { get; set; }
        [BindProperty]
        public string PreferredPaymentMethod { get; set; }
        [BindProperty]
        public int PreferredPaymentMethodChance { get; set; }
        [BindProperty]
        public string GcRecord { get; set; }
        [BindProperty]
        public int GcRecordChance { get; set; }

        public void OnPostGenerate()
        {
            var random = new Random();
            var cSessionId = Guid.NewGuid();
            for (var i = 0; i < Quantity; i++)
            {
                var cCustomer = new Models.Customer
                {
                    FirstName = FirstName.Equals("Random") ? GetRandomString() : GetRandomFromList("firstNames"),
                    LastName = FirstName.Equals("Random") ? GetRandomString() : GetRandomFromList("lastNames"),
                };
                cCustomer.Email = Email.Equals("Random")
                    ? GetRandomString()
                    : $"{cCustomer.FirstName}.{cCustomer.LastName}" + GetRandomMailSuffix();
                if (FillOptionalProperties)
                {
                    if (random.Next(0, 100) <= MiddleNameChance)
                        cCustomer.MiddleName = MiddleName.Equals("Random") ? GetRandomString() : GetRandomFromList("firstNames");
                    if (random.Next(0, 100) <= SecondaryEmailChance)
                        cCustomer.SecondaryEmail = SecondaryEmail.Equals("Random") ? GetRandomString() : $"{cCustomer.FirstName}.{cCustomer.LastName}" + GetRandomMailSuffix();
                    if (random.Next(0, 100) <= PhoneNumberChance)
                        cCustomer.PhoneNumber = "+" + GetRandomInt();
                    if (random.Next(0, 100) <= SecondaryPhoneNumberChance)
                        cCustomer.SecondaryPhoneNumber = "+" + GetRandomInt();
                    if (random.Next(0, 100) <= DateOfBirthChance)
                        cCustomer.DateOfBirth = DateOfBirth.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                    if (random.Next(0, 100) <= GenderChance)
                        cCustomer.Gender = Gender.Equals("Random") ? GetRandomString() : GetRandomFromList("genders");
                    if (random.Next(0, 100) <= NationalityChance)
                        cCustomer.Nationality = Nationality.Equals("Random") ? GetRandomString() : GetRandomFromList("countries");
                    if (random.Next(0, 100) <= AddressLine1Chance)
                        cCustomer.AddressLine1 = AddressLine1.Equals("Random") ? GetRandomString() : GetRandomFromList("addressLines");
                    if (random.Next(0, 100) <= AddressLine2Chance)
                        cCustomer.AddressLine2 = AddressLine2.Equals("Random") ? GetRandomString() : GetRandomFromList("addressLines");
                    if (random.Next(0, 100) <= CityChance)
                        cCustomer.City = City.Equals("Random") ? GetRandomString() : GetRandomFromList("cities");
                    if (random.Next(0, 100) <= StateChance)
                        cCustomer.State = State.Equals("Random") ? GetRandomString() : GetRandomFromList("states");
                    if (random.Next(0, 100) <= CountryChance)
                        cCustomer.Country = Country.Equals("Random") ? GetRandomString() : GetRandomFromList("countries");
                    if (random.Next(0, 100) <= PostalCodeChance)
                        cCustomer.PostalCode = PostalCode.Equals("Random") ? GetRandomString() : GetRandomInt(10000,100000).ToString();
                    if (random.Next(0, 100) <= IsActiveChance)
                        cCustomer.IsActive = GetRandomBool();
                    if (random.Next(0, 100) <= LastOnlineChance)
                        cCustomer.LastOnline = LastOnline.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                    if (random.Next(0, 100) <= CreatedAtChance)
                        cCustomer.CreatedAt = CreatedAt.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                    if (random.Next(0, 100) <= UpdatedAtChance)
                        cCustomer.UpdatedAt = UpdatedAt.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                    if (random.Next(0, 100) <= PreferredLanguageChance)
                        cCustomer.PreferredLanguage = PreferredLanguage.Equals("Random") ? GetRandomString() : GetRandomFromList("preferredLanguages");
                    if (random.Next(0, 100) <= PreferredPaymentMethodChance)
                        cCustomer.PreferredPaymentMethod = PreferredPaymentMethod.Equals("Random") ? GetRandomString() : GetRandomFromList("preferredPaymentMethods");
                    if (random.Next(0, 100) <= GcRecordChance)
                        cCustomer.GcRecord = GcRecord.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                }

                var shardId = cCustomer.HasGcRecord ? 2 : 1;
                unitOfWork.Customer.Add(cCustomer, cSessionId, shardId);
            }
        }
    }
}

DatabaseManager.Web/Pages/Generators/Order/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseManager.Web.Pages.Generators.Order
{
    public class IndexModel(IUnitOfWork unitOfWork, IConfiguration configuration) : CustomPageModel<IndexModel>(configuration)
    {
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public bool FillOptionalProperties { get; set; }
        [BindProperty]
        public bool SetReferences { get; set; }
        [BindProperty]
        public string TotalAmount { get; set; }
        [BindProperty]
        public string OrderDate { get; set; }
        [BindProperty]
        public string Status { get; set; }
        [BindProperty]
        public string GcRecord { get; set; }
        [BindProperty]
        public int GcRecordChance { get; set; }

        public void OnPostGenerate()
        {
            var random = new Random();
            var cSessionId = Guid.NewGuid();
            var customerIdsShard1 = unitOfWork.Customer.GetAllIds(1);
            var customerIdsShard2 = unitOfWork.Customer.GetAllIds(2);
            for (var i = 0; i < Quantity; i++)
            {
                var cOrder = new Models.Order
                {
                    TotalAmount = GetRandomInt(),
                    OrderDate = OrderDate.Equals("Random") ? GetRandomDateTime() : DateTime.Now,
                    Status = Status.Equals("Random") ? GetRandomString() : GetRandomFromList("orderStatus"),
                };
                if (FillOptionalProperties)
                {
                    if (random.Next(0, 100) <= GcRecordChance)
                        cOrder.GcRecord = GcRecord.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                }

                cOrder.CustomerId = GetRandomFromIds(cOrder.HasGcRecord ? customerIdsShard2 : customerIdsShard1);
                var shardId = cOrder.HasGcRecord ? 2 : 1;
                unitOfWork.Order.Add(cOrder, cSessionId, shardId);
            }
        }
    }
}

DatabaseManager.Web/Pages/Generators/Payment/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseManager.Web.Pages.Generators.Payment
{
    public class IndexModel(IUnitOfWork unitOfWork, IConfiguration configuration) : CustomPageModel<IndexModel>(configuration)
    {
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public bool FillOptionalProperties { get; set; }
        [BindProperty]
        public bool SetReferences { get; set; }
        [BindProperty]
        public string Amount { get; set; }
        [BindProperty]
        public string PaymentDate { get; set; }
        [BindProperty]
        public string PaymentMethod { get; set; }
        [BindProperty]
        public string GcRecord { get; set; }
        [BindProperty]
        public int GcRecordChance { get; set; }

        public void OnPostGenerate()
        {
            var random = new Random();
            var cSessionId = Guid.NewGuid();
            var customerIdsShard1 = unitOfWork.Customer.GetAllIds(1);
            var customerIdsShard2 = unitOfWork.Customer.GetAllIds(2);
            for (var i = 0; i < Quantity; i++)
            {
                var cPayment = new Models.Payment
                {
                    Amount = GetRandomInt(),
                    PaymentDate = PaymentDate.Equals("Random") ? GetRandomDateTime() : DateTime.Now,
                    PaymentMethod = PaymentMethod.Equals("Random") ? GetRandomString() : GetRandomFromList("preferredPaymentMethods"),
                };
                if (FillOptionalProperties)
                {
                    if (random.Next(0, 100) <= GcRecordChance)
                        cPayment.GcRecord = GcRecord.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                }
                cPayment.CustomerId = GetRandomFromIds(cPayment.HasGcRecord ? customerIdsShard2 : customerIdsShard1);
                var shardId = cPayment.HasGcRecord ? 2 : 1;
                unitOfWork.Payment.Add(cPayment, cSessionId, shardId);
            }
        }
    }
}

DatabaseManager.Web/Pages/Generators/Product/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseManager.Web.Pages.Generators.Product
{
    public class IndexModel(IUnitOfWork unitOfWork, IConfiguration configuration) : CustomPageModel<IndexModel>(configuration)
    {
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public bool FillOptionalProperties { get; set; }
        [BindProperty]
        public bool SetReferences { get; set; }
        [BindProperty]
        public string Name { get; set; }
        [BindProperty]
        public string Description { get; set; }
        [BindProperty]
        public int DescriptionChance { get; set; }
        [BindProperty]
        public string Category { get; set; }
        [BindProperty]
        public int CategoryChance { get; set; }
        [BindProperty]
        public string GcRecord { get; set; }
        [BindProperty]
        public int GcRecordChance { get; set; }

        public void OnPostGenerate()
        {
            var random = new Random();
            var cSessionId = Guid.NewGuid();
            for (var i = 0; i < Quantity; i++)
            {
                var cProduct = new Models.Product
                {
                    Name = Name.Equals("Random") ? GetRandomString() : GetRandomFromList("productNames"),
                    Price = GetRandomDecimal(),
                    Stock = GetRandomInt()
                };
                if (FillOptionalProperties)
                {
                    if (random.Next(0, 100) <= DescriptionChance)
                        cProduct.Description = Description.Equals("Random") ? GetRandomString() : GetRandomFromList("productDescription");
                    if (random.Next(0,100) <= CategoryChance)
                        cProduct.Category = Category.Equals("Random") ? GetRandomString() : GetRandomFromList("productCategories");
                    if (random.Next(0, 100) <= GcRecordChance) 
                        cProduct.GcRecord = GcRecord.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                }
                var shardId = cProduct.HasGcRecord ? 2 : 1;
                unitOfWork.Product.Add(cProduct, cSessionId, shardId);
            }
        }
    }
}

DatabaseManager.Web/Pages/Generators/Review/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;

namespace DatabaseManager.Web.Pages.Generators.Review
{
    public class IndexModel(IUnitOfWork unitOfWork, IConfiguration configuration) : CustomPageModel<IndexModel>(configuration)
    {
        [BindProperty]
        public int Quantity { get; set; }
        [BindProperty]
        public bool FillOptionalProperties { get; set; }
        [BindProperty]
        public bool SetReferences { get; set; }
        [BindProperty]
        public string Rating { get; set; }
        [BindProperty]
        public string ReviewDate { get; set; }
        [BindProperty]
        public string Content { get; set; }
        [BindProperty]
        public int ContentChance { get; set; }
        [BindProperty]
        public string GcRecord { get; set; }
        [BindProperty]
        public int GcRecordChance { get; set; }
        [BindProperty]
        public int CustomerChance { get; set; }

        public void OnPostGenerate()
        {
            var random = new Random();
            var cSessionId = Guid.NewGuid();
            var customerIdsShard1 = new List<Guid>();
            var customerIdsShard2 = new List<Guid>();
            if (SetReferences)
            {
                customerIdsShard1 = unitOfWork.Customer.GetAllIds(1);
                customerIdsShard2 = unitOfWork.Customer.GetAllIds(2);
            }
            
            for (var i = 0; i < Quantity; i++)
            {
                var cReview = new Models.Review
                {
                    Rating = GetRandomInt(1, 5),
                    ReviewDate = ReviewDate.Equals("Random") ? GetRandomDateTime() : DateTime.Now,
                    Content = Content.Equals("Random") ? GetRandomString() : GetRandomFromList("reviewContent")
                };
                if (FillOptionalProperties)
                {
                    if (random.Next(0, 100) <= GcRecordChance)
                        cReview.GcRecord = GcRecord.Equals("Random") ? GetRandomDateTime() : DateTime.Now;
                }

                if (SetReferences)
                {
                    if (random.Next(0, 100) < CustomerChance) 
                        cReview.CustomerId = GetRandomFromIds(cReview.HasGcRecord ? customerIdsShard2 : customerIdsShard1);
                }
                var shardId = cReview.HasGcRecord ? 2 : 1;
                unitOfWork.Review.Add(cReview, cSessionId, shardId);
            }
        }
    }
}

DatabaseManager.Web/Pages/Generators/Review/Index.cshtml
@page
@model DatabaseManager.Web.Pages.Generators.Review.IndexModel
@{
}
<div class="container-fluid p-5">
    <div class="row pt-4 align-items-center">
        <div class="col-9">
            <h2 class="text-primary">@Model.ToString() Generator</h2>
        </div>
        <form asp-page-handler="Generate" method="post">
            <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-top: 20px; display: flex; justify-content: space-between; align-items: center;">
                <p>Quantity: <input type="number" min="1" value="1" class="text-secondary" style="height: 25px;" name="quantity"></p>
                <p style="display: flex; align-items: center;">
                    Fill optional properties
                    <input type="checkbox" id="FillOptionalProperties" asp-for="FillOptionalProperties" class="text-secondary" style="height: 25px; width: 25px;">
                </p>
                <p style="display: flex; align-items: center;">
                    Set References:&nbsp;
                    <input type="checkbox" id="SetReferences" asp-for="SetReferences" class="text-secondary" style="height: 25px; width: 25px;" >
                </p>
            </div>
            <h3>Required:</h3>
            <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; display: flex; justify-content: space-between; align-items: center;">
                <p>
                    Rating:
                    <select class="text-secondary" style="height: 25px;" name="rating">
                        <option value="Random">Random</option>
                    </select>
                </p>
                <p>
                    ReviewDate:
                    <select class="text-secondary" style="height: 25px;" name="reviewDate">
                        <option value="Random">Random</option>
                        <option value="Now">Now</option>
                    </select>
                </p>
                <p>
                    Content:
                    <select class="text-secondary" style="height: 25px;" name="content">
                        <option value="Random">Random</option>
                        <option value="ReviewContents">ReviewContents</option>
                    </select>
                </p>
            </div>
            <div id="optionalSection" style="display: none;">
                <h3>Optional:</h3>
                <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; display: flex; justify-content: space-between; align-items: center;">
                    <p>
                        GcRecord:
                        <select class="text-secondary" style="height: 25px;" name="gcRecord">
                            <option value="Random">Random</option>
                            <option value="Now">Now</option>
                        </select>
                        Chance:&nbsp;<input type="number" min="0" max="100" value="50" style="height: 25px;" name="gcRecordChance">
                    </p>
                </div>
            </div>
            <div id="referenceSection" style="display: none;">
                <h3>References:</h3>
                <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; display: flex; justify-content: space-between; align-items: center;">
                    <p>
                        Customer:
                        Chance:&nbsp;<input type="number" min="0" max="100" value="50" style="height: 25px;" name="customerChance">
                    </p>
                </div>
            </div>
            <div class="col-10" style="padding: 20px">
                <button type="submit" class="btn btn-outline-danger">
                    <div class="d-flex justify-content-center">
                        <i class="bi bi-database-up"></i>&nbsp;Generate
                    </div>
                </button>
            </div>
        </form>
    </div>
    <br />
</div>

<script>
    document.getElementById('FillOptionalProperties').addEventListener('change', function () {
        document.getElementById('optionalSection').style.display = this.checked ? 'block' : 'none';
    });
    document.getElementById('SetReferences').addEventListener('change', function () {
        document.getElementById('referenceSection').style.display = this.checked ? 'block' : 'none';
    });
</script>