DatabaseManager.Web/Pages/Performance/Index.cshtml.cs
using DatabaseManager.DataAccess.Repository.IRepository;
using DatabaseManager.Models;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using System.Globalization;

namespace DatabaseManager.Web.Pages.Performance
{
    public class IndexModel(IUnitOfWork unitOfWork, IToastNotification toastNotification, IEnumerable<Models.Performance> performances, IConfiguration configuration) : CustomPageModel<IndexModel>(configuration)
    {
        [BindProperty(SupportsGet = true)]
        public int CurrentPage { get; set; } = 1;
        [BindProperty(SupportsGet = true)]
        public int RowCount { get; set; }
        [BindProperty(SupportsGet = true)]
        public IEnumerable<Models.Performance> Performances { get; set; } = performances;
        [BindProperty]
        public int Runs { get; set; }
        [BindProperty]
        public string Table { get; set; }
        [BindProperty]
        public string Type { get; set; }

        public void OnGet(int pageNumber = 1)
        {
            CurrentPage = pageNumber;
            Performances = unitOfWork.Performance.GetPagedEntities(x => x.Id, pageNumber, 10);
            RowCount = unitOfWork.Performance.GetRowCount();
        }

        public void OnPostAnalyze()
        {
            var results = new List<TimeSpan>();
            var sqlCommand = GetSqlCommand();
            using var dbConnection = unitOfWork.GetDbConnection();
            for (var i = 0; i < Runs; i++)
            {
                var startTime = DateTime.Now;
                dbConnection.Open();
                using var command = dbConnection.CreateCommand();
                command.CommandText = sqlCommand;
                command.ExecuteNonQuery();
                dbConnection.Close();
                var endTime = DateTime.Now;
                results.Add(endTime-startTime);
            }
            var totalSeconds = results.Sum(ts => ts.TotalSeconds);
            var averageSeconds = totalSeconds / results.Count;
            var cPerformance = new Models.Performance
            {
                Runs = Runs,
                Table = Table,
                Type = Type,
                AverageSeconds = averageSeconds
            };
            unitOfWork.Performance.Add(cPerformance);
            unitOfWork.SaveChanges();
            toastNotification.AddSuccessToastMessage($"Average duration: {averageSeconds} seconds");
            OnGet();
        }

        private string GetSqlCommand()
        {
            if (Table.Equals("Customer"))
            {
                var cFirstname = GetRandomFromList("firstNames");
                switch (Type)
                {
                    case "Select":
                        return $"SELECT * FROM Customers WHERE FirstName LIKE '%{cFirstname}%' AND GcRecord is NULL";
                    case "Add":
                    {
                        var cLastName = GetRandomFromList("lastNames");
                        var cEmail = $"{cFirstname}.{cLastName}" + GetRandomMailSuffix();
                        return $"INSERT INTO Customers (Id, FirstName, LastName, Email, IsActive) VALUES ('{Guid.NewGuid()}','{cFirstname}', '{cLastName}', '{cEmail}', '{1}')";
                    }
                    case "Update":
                    {
                        var uFirstName = GetRandomFromList("firstNames");
                        return $"UPDATE Customers SET FirstName = '{uFirstName}' WHERE FirstName LIKE '%{cFirstname}%' AND GcRecord is NULL";
                    }
                    case "Delete":
                        return $"DELETE FROM Customers WHERE FirstName LIKE '%{cFirstname}%' AND GcRecord is NULL";
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            if (Table.Equals("Order"))
            {
                var cCustomerId = GetRandomFromIds(unitOfWork.Customer.GetAllIds(1));
                switch (Type)
                {
                    case "Select":
                        return $"SELECT * FROM Orders WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    case "Add":
                    {
                        var cOrderDate = GetRandomDateTime().ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
                        var cTotalAmount = GetRandomDecimal().ToString(CultureInfo.InvariantCulture);
                        return $"INSERT INTO Orders (Id, CustomerId, OrderDate, TotalAmount, Status) VALUES ('{Guid.NewGuid()}','{cCustomerId}', '{cOrderDate}', '{cTotalAmount}', 'Pending')";
                    }
                    case "Update":
                    {
                        var uCustomerId = GetRandomFromIds(unitOfWork.Customer.GetAllIds());
                        return $"UPDATE Orders SET CustomerId = '{uCustomerId}' WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    }
                    case "Delete":
                        return $"DELETE FROM Orders WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            if (Table.Equals("Payment"))
            {
                var cCustomerId = GetRandomFromIds(unitOfWork.Customer.GetAllIds(1));
                switch (Type)
                {
                    case "Select":
                        return $"SELECT * FROM Payments WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    case "Add":
                    {
                        var cPaymentDate = GetRandomDateTime().ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
                        var cAmount = GetRandomDecimal().ToString(CultureInfo.InvariantCulture);
                        return $"INSERT INTO Payments (Id, CustomerId, PaymentDate, Amount, PaymentMethod) VALUES ('{Guid.NewGuid()}','{cCustomerId}', '{cPaymentDate}', '{cAmount}', 'BloomPay')";
                    }
                    case "Update":
                    {
                        var uCustomerId = GetRandomFromIds(unitOfWork.Customer.GetAllIds());
                        return $"UPDATE Payments SET CustomerId = '{uCustomerId}' WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    }
                    case "Delete":
                        return $"DELETE FROM Payments WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            if (Table.Equals("Product"))
            {
                var cName = GetRandomFromList("productNames");
                switch (Type)
                {
                    case "Select":
                        return $"SELECT * FROM Products WHERE Name LIKE '%{cName}%' AND GcRecord is NULL";
                    case "Add":
                    {
                        var cPrice = GetRandomDecimal().ToString(CultureInfo.InvariantCulture);
                        var cStock = GetRandomInt(1, 9999);
                        return $"INSERT INTO Products (Id, Name, Price, Stock) VALUES ('{Guid.NewGuid()}','{cName}', '{cPrice}', '{cStock}')";
                    }
                    case "Update":
                    {
                        var uName = GetRandomFromList("productNames");
                        return $"UPDATE Products SET Name = '{uName}' WHERE Name LIKE '%{cName}%' AND GcRecord is NULL";
                    }
                    case "Delete":
                        return $"DELETE FROM Products WHERE Name LIKE '%{cName}%' AND GcRecord is NULL";
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }

            if (Table.Equals("Review"))
            {
                var cCustomerId = GetRandomFromIds(unitOfWork.Customer.GetAllIds(1));
                switch (Type)
                {
                    case "Select":
                        return $"SELECT * FROM Reviews WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    case "Add":
                    {
                        var cReviewDate = GetRandomDateTime().ToString("yyyy-MM-dd HH:mm:ss", CultureInfo.InvariantCulture);
                        var cRating = GetRandomInt(1, 5);
                        return $"INSERT INTO Reviews (Id, CustomerId, ReviewDate, Rating, Content) VALUES ('{Guid.NewGuid()}','{cCustomerId}', '{cReviewDate}', '{cRating}', 'Hervorragende App! Sehr benutzerfreundlich und effizient.')";
                    }
                    case "Update":
                    {
                        var uCustomerId = GetRandomFromIds(unitOfWork.Customer.GetAllIds());
                        return $"UPDATE Reviews SET CustomerId = '{uCustomerId}' WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    }
                    case "Delete":
                        return $"DELETE FROM Reviews WHERE CustomerId = '{cCustomerId}' AND GcRecord is NULL";
                    default:
                        throw new ArgumentOutOfRangeException();
                }
            }
            throw new NotImplementedException();
        }
    }
}

DatabaseManager.Web/Pages/Performance/Index.cshtml
@page
@model DatabaseManager.Web.Pages.Performance.IndexModel
@{
}

<div class="container-fluid p-5">
    <div class="row pt-4 align-items-center">
        <div class="col-9">
            <h2 class="text-primary">Performance Analyzer</h2>
        </div>
        <form asp-page-handler="Analyze" method="post">
            <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-top: 20px; display: flex; justify-content: space-between; align-items: center;">
                <p>Runs: <input type="number" min="1" value="5" class="text-secondary" style="height: 25px;" name="runs"></p>
                <p>
                    Tables:
                    <select class="text-secondary" style="height: 25px;" name="table">
                        <option value="Customer">Customer</option>
                        <option value="Order">Order</option>
                        <option value="Payment">Payment</option>
                        <option value="Product">Product</option>
                        <option value="Review">Review</option>
                    </select>
                </p>
                <p>
                    Type:
                    <select class="text-secondary" style="height: 25px;" name="type">
                        <option value="Select">Select</option>
                        <option value="Add">Add</option>
                        <option value="Update">Update</option>
                        <option value="Delete">Delete</option>
                    </select>
                </p>
            </div>
            <div class="col-10" style="padding: 20px">
                <button type="submit" class="btn btn-outline-primary">
                    <div class="d-flex justify-content-center">
                        <i class="bi bi-database-gear"></i>&nbsp;Analyze
                    </div>
                </button>
            </div>
        </form>
        <div class="col-10" style="border: 1px solid #ccc; border-radius: 10px; padding: 20px; margin-top: 20px; overflow: auto;">
            <h3 class="text-secondary">Performance Overview:</h3>
            <table class="table table-bordered table-striped" style="width: 100%">
                <thead>
                    <tr class="table-primary">
                        <th>
                            RunAt
                        </th>
                        <th>
                            Runs
                        </th>
                        <th>
                            Table
                        </th>
                        <th>
                            Type
                        </th>
                        <th>
                            AverageSeconds
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var obj in Model.Performances)
                    {
                        <input type="hidden" value="@obj.Id" />
                        <tr>
                            <td width="20%">
                                @obj.RunAt
                            </td>
                            <td width="20%">
                                @obj.Runs
                            </td>
                            <td width="20%">
                                @obj.Table
                            </td>
                            <td width="20%">
                                @obj.Type
                            </td>
                            <td width="20%">
                                @obj.AverageSeconds
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div class="pagination-container btn-toolbar" role="toolbar">
                <div class="btn-group me-2" role="group">
                    @{
                        var currentPage = Model.CurrentPage;
                        var totalPages = (Model.RowCount + 9) / 10;
                    }
                    <!-- Erste Seite -->
                    @if (currentPage > 2)
                    {
                        <a class="btn btn-primary" href="?pageNumber=1">1</a>
                    }
                    <!-- Vorherige Seite -->
                    @if (currentPage > 1)
                    {
                        <a class="btn btn-primary" href="?pageNumber=@(currentPage - 1)">@((currentPage - 1))</a>
                    }
                    <!-- Aktuelle Seite -->
                    <a class="btn btn-primary active" href="?pageNumber=@currentPage">@currentPage</a>
                    <!-- Nächste Seite -->
                    @if (currentPage < totalPages)
                    {
                        <a class="btn btn-primary" href="?pageNumber=@(currentPage + 1)">@((currentPage + 1))</a>
                    }
                    <!-- Letzte Seite -->
                    @if (currentPage < totalPages - 1)
                    {
                        <a class="btn btn-primary" href="?pageNumber=@totalPages">@totalPages</a>
                    }
                </div>
            </div>
        </div>
    </div>
    <br />
</div>